import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "@/components/BlogCard";

const graphcms = new GraphQLClient(
  "https://api-ap-northeast-1.hygraph.com/v2/clisu39zr011n01tfeorp89g4/master"
);

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      photo {
        createdBy {
          id
        }
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
  };
}

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.title}>
          <h2>NEXT.JS-Blog</h2>
        </div>
        <div className={styles.gridWrapper}>
          {posts.map((post) => (
            <BlogCard
              photo={post.photo}
              title={post.title}
              author={post.author}
              date={post.datePublished}
              slug={post.slug}
              key={post.id}
            />
          ))}
        </div>
      </main>
    </>
  );
}
